name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: budget
          MYSQL_USER: root
          MYSQL_PASSWORD: helloworld123
        ports:
          - 3306:3306

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: budget
      DB_USERNAME: root
      DB_PASSWORD: helloworld123

    steps:
      - uses: actions/checkout@v4
      - name: PHP setup
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - name: Install Composer
        run: composer install

      - name: Installion command
        run: php artisan budget:install

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Migrate database
        run: php artisan migrate

      - name: Run tests
        run: ./vendor/bin/phpunit
