name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: PHP setup
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"

      - name: Install Composer
        run: composer install --no-dev -o 

      - name: Installion command
        run: php artisan budget:install

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Run tests
        run: ./vendor/bin/phpunit
