name: Budget-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow
        uses: actions/checkout@v4

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer
        run: composer install

      - name: Run PHPCS
        run: ./vendor/bin/phpcs

  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.APP_DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.APP_DATABASE }}
        ports:
          - 3306:3306

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: ${{ secrets.APP_DATABASE }}
      DB_USERNAME: root
      DB_PASSWORD: ${{ secrets.APP_DATABASE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer
        run: composer install

      - name: Install node dependencies
        run: php artisan budget:install

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Migrate database
        run: php artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Run browser tests
        env:
          APP_URL: http://127.0.0.1:8000
          DUSK_DRIVER_URL: http://localhost:9515
        run: |
          php artisan dusk:chrome-driver --detect
          ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
          php artisan serve &
          php artisan dusk
