name: Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: helloworld123
          MYSQL_DATABASE: budget
        ports:
          - 3306:3306

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: budget
      DB_USERNAME: root
      DB_PASSWORD: helloworld123

    steps:
      - uses: actions/checkout@v4
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install Composer
        run: composer install

      - name: Install node dependencies
        run: php artisan budget:install

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"

      - name: Migrate database
        run: php artisan migrate --force

      - name: Run tests
        run: ./vendor/bin/phpunit

      - name: Run browser tests
        run: |
          php artisan dusk:chrome-driver --detect
          ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &
          php artisan serve --no-reload &
          timeout 15 bash -c 'until curl -s http://127.0.0.1:8000 > /dev/null; do sleep 1; done'
          php artisan dusk
